FROM ubuntu

RUN apt-get update -y
RUN apt-get install nginx -y
WORKDIR /usr/share/nginx/html/
RUN rm -rf index.html
WORKDIR /var/www/html/
RUN rm -rf index.nginx-debian.html



COPY index.html /var/www/html/
COPY index.html /usr/share/nginx/html/





CMD ["nginx","-g","daemon off;"]
EXPOSE 80